# Site settings
name: Xiaoshimimi's Travel Blog
title: Xiaoshimimi's Travel Blog
email: xiaoshimimi@gmail.com
author: Yue Chen
resume_site: http://blog.sina.com.cn/xiaoshimimi
github: https://github.com/xiaoshimimi/
description: I'm going to move blog.sina.com.cn/xiaoshimimi to this site.
meta_description: 陈悦;旅游博客
baseurl: "/travel" # the subpath of your site, e.g. /blog
url: "https://xiaoshimimi.github.io" # the base hostname & protocol for your site
motto: Be happy every day!
banner: 人类一思考上帝就发笑，所以我们要常常思考以取悦上帝。
permalink: /:year/:month/:day/:title/
paginate: 10

twitter_username: xiaoshimimi
github_username:  xiaoshimimi
highlighter: rouge

# Build settings
md: kramdown
markdown: kramdown
gems:
  - jekyll-paginate
